  
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: script-jd-sign

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发      - 
  schedule: # 计划任务触发
    - cron: '15 6 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点15分 
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: npm ci && node index.js "${COOKIE}"
