# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: script-jd-sign

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "3 1 * * *"

jobs:
  run-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: npm ci && node index.js "${COOKIE}"
